### PR TITLE
Ignore unknown flags

### PR DESCRIPTION
**Pull request by stevo-f3**
Fixes https://github.com/open-policy-agent/kube-mgmt/issues/136

### CODE REVIEW

**Comment by anderseknert** [comment]
I presume you've tested this locally? :)

**Comment by stevo-f3** [comment]
@anderseknert yes, I built binary locally from master and from PR branch, and ran `~/go/bin/kube-mgmt --logtostderr`.
Binary built from master outputs error that logtostderr is unknown flag and usage:
```bash
$ ~/go/bin/kube-mgmt --logtostderr
Error: unknown flag: --logtostderr
Usage:
  kube-mgmt [flags]

Flags:
      --enable-data                                  whether to automatically discover data from correctly labelled ConfigMaps
      --enable-policies                              whether to automatically discover policies from ConfigMaps (default true)
  -h, --help                                         help for kube-mgmt
      --kubeconfig string                            set path to kubeconfig manually
      --opa-allow-insecure                           allow insecure https connections to OPA
      --opa-auth-token string                        set authentication token for OPA API endpoint
      --opa-auth-token-file string                   set file containing authentication token for OPA API endpoint
      --opa-ca-file string                           set file containing certificate authority for OPA certificate
      --opa-url string                               set URL of OPA API endpoint (default "http://localhost:8181/v1")
      --pod-name string                              set pod name (required for admission registration ownership)
      --pod-namespace string                         set pod namespace (required for admission registration ownership)
      --policies strings                             automatically load policies from these namespaces (default [opa,kube-federation-scheduling-policy])
      --policy-label string                          replace label openpolicyagent.org/policy (default "openpolicyagent.org/policy")
      --policy-value string                          replace value rego (default "rego")
      --replicate [group/]version/resource           replicate namespace-level resources (default [])
      --replicate-cluster [group/]version/resource   replicate cluster-level resources (default [])
      --replicate-path string                        set path to replicate data into (default "kubernetes")
      --require-policy-label                         only load policies out of labelled configmaps
  -v, --version                                      print version and exit

unknown flag: --logtostderr
```

while binary built from PR branch passes flag parsing, fails at step afterwards since no other mandatory config/runtime provided:
```bash
$ ~/go/bin/kube-mgmt --logtostderr
WARN[0000] First line of log stream.
FATA[0000] Failed to load kubeconfig: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```

**Comment by anderseknert** [comment]
Thanks Stevo!

**Review by anderseknert — APPROVED** [review]

**Comment by anderseknert** [comment]
We can probably try to cut a release sometime this week.

**Comment by matejb-form3** [comment]
@anderseknert is release with this fix possible to happen this/next week? 🙏🏻

**Comment by anderseknert** [comment]
We're all pretty swamped preparing for the OPA release this week, but we could probably get it out on Friday or early next week :)

**Comment by srenatus** [comment]
❤️ here you go https://github.com/open-policy-agent/kube-mgmt/releases/tag/4.1.0

**Pull request merged**
