### PR TITLE
Fixes issues with ConfigMap annotations

### PR DESCRIPTION
**Pull request by rg2011**
This PR addresses two issues with how ConfigMap annotations are handled:

- #90
- #131

### CODE REVIEW

**Review by anderseknert — COMMENTED** [review]
The change looks good to me! Thanks for working on this 👍 I'm not too sure about introducing another dependency to be used only in a single location though, at least not if it doesn't mean a **huge** improvement where it's used, and I can't see that being the case here. If you feel that kube-mgmt as a whole would benefit from that library, I'd prefer to see another PR introducing that dependency, along with applying it where it results in an improvement. Just my two cents though :)

**Review by anderseknert — APPROVED** [review]

**Comment by rg2011** [comment]
> The change looks good to me! Thanks for working on this 👍 I'm not too sure about introducing another dependency to be used only in a single location though, at least not if it doesn't mean a **huge** improvement where it's used, and I can't see that being the case here. If you feel that kube-mgmt as a whole would benefit from that library, I'd prefer to see another PR introducing that dependency, along with applying it where it results in an improvement. Just my two cents though :)

Hi, thanks for reviewing! Yes, for this use case hashicorp/multierror can be easily replaced with a small error list. I have removed the dependency and rebased.

**Comment by anderseknert** [comment]
Splendid! Thanks @rg2011 👍

**Comment by rg2011** [comment]
Hi @anderseknert , would you please merge the PR? or is there something else I'd need to do?

**Comment by anderseknert** [comment]
Hey @rg2011 ! Nothing else you need to do, sorry for the delay... was just giving some time for others to review, but let's get it merged.

**Pull request merged**
