### PR TITLE
Add arm64 support using buildx

### PR DESCRIPTION
**Pull request by odidev**
The following file has been created and modified:
Added support for arm64 using buildx in .github/workflows/releases.yaml and justfile to build and release docker image for both amd64 and arm64 platforms.
Updated Dockerfile to add support for arm64.

Signed-off-by: odidev odidev@puresoftware.com

### CODE REVIEW

**Review by eshepelyuk — CHANGES_REQUESTED** [review]
1. As far as I see - the image building for tests/CI should be kept in skaffold only, but the build for release should be handled completely by `buildx`
1. there should be a single `just` recipe to build and push all the images _during the release job_, there's no need to introduce a separate recipe / gh action step.

**Review by eshepelyuk — COMMENTED** [review]
How many images should be pushed to registry after this change ?
Should not the images for differetn architecture be tagged separately ?

**Comment by srenatus** [comment]
@eshepelyuk I think this follows the same pattern set out by OPA's static images. We'll end up pushing a manifest to dockerhub, and it'll look like this:

image

**Comment by eshepelyuk** [comment]
After some basic research it seems that for multiplatform builds using skaffold it is required either
* Implement custom buildscript https://skaffold.dev/docs/pipeline-stages/builders/custom/
* Use `ko` builder https://skaffold.dev/docs/pipeline-stages/builders/ko/

I will try to play with `ko` first and evaluate it.

**Pull request closed without merging**
