### PR TITLE
Introducing bumpversion

### PR DESCRIPTION
**Pull request by phisco**
In order to smooth the release process, I introduced [bumpversion](https://pypi.org/project/bumpversion/).

Bumpversion will take care of bumping the version in all the needed files, commit the changes and tag them accordingly to semver. We'll still need to create the release and write the release notes by hand, but at least we can be sure releases will update all the needed files.

### CODE REVIEW

**Comment by angelbarrera92** [comment]
Makes sense to me!

The only note I can add here is that you have to consider modifying the `charts/opa/Chart.yml` file in this PR to make it working properly. 
As far as I can see, the `Chart.yml`  file has defined `appVersion: 0.15.1`; It should be: `0.12.1` instead of `0.15.1` otherwise im not sure `bumpversion` will work as expected.

**Review by angelbarrera92 — CHANGES_REQUESTED** [review]
Take a look at the previous comment,

**Comment by phisco** [comment]
I know the chart versioning is messed up. I think it was binded to opa versions before we moved it here and now we should probably bump it back to be in sync with kube-mgmt, but I was not sure how to handle it. Don't you think that bumping it back would mess the chart versioning? Should we reset it, @angelbarrera92?

**Comment by angelbarrera92** [comment]
> If #104 will be merged, this PR should be deprecated.

#104 looks better. Let's close this one

**Pull request closed without merging**
