### PR TITLE
Update kube-mgmt dependencies

### PR DESCRIPTION
**Pull request by rg2011**
This PR upgrades the dependencies of kube-mgmt (issue #123), from pre-module world of 2019:

| dependency | from | to |
| -- | -- | -- |
| k8s.io/client-go | v0.0.0-20190313235726-6ee68ca5fd83 | v0.23.4 |
| k8s.io/api | v0.0.0-20190313235455-40a48860b5ab | v0.23.4 |
| k8s.io/apimachinery | v0.0.0-20190313205120-d7deff9243b1 | v0.23.4 |
| github.com/spf13/cobra | v0.0.0-20170612063610-b4dbd37a0183 | v1.3.0 |
| github.com/Sirupsen/logrus | v0.11.4 | v1.8.1 |
| github.com/pkg/errors | v0.8.2-0.20190227000051-27936f6d90f9 | standard "errors" package |

The code has been minimally changed to run `go test ./...`, `go vet ./...` and [staticcheck](https://staticcheck.io/) `staticcheck ./...` without errors or warnings. The changes are:

- cmd/kube-mgmt/flag_test.go: The error message text has changed slightly.
- pkg/configmap/configmap.go: `codecs.DirectCodecFactory` was replaced by `codecs.WithoutConversionCodecFactory` in client-go release 0.16.0 (see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals)
- pkg/configmap/configmap.go: `Patch` function now requires Context and PatchOptions{} parameters.
- pkg/data/generic.com: `resource.List` function now requires a Context.
- pkg/data/generic.com: `github.com/pkg/errors` replaced with standard `errors` package.
- pkg/data/generic.com: field internal is unused in GenericSync type (staticcheck error)
- pkg/data/generic.com: unreachable case clause: errOPA will always match before errKubernetes (staticcheck error).
- pkg/data/generic_test.com: unstructured.Unstructured composite literal uses unkeyed fields (go vet error)
- pkg/opa/opa.go:31:9: unnecessary use of fmt.Sprintf (staticcheck error)

### CODE REVIEW

**Comment by rg2011** [comment]
> Thanks for the fast-forward into the future 👏 🎉
> 
> Given that the amount of vendored code in this commit is enormous, I'd slightly prefer keeping your changes to the original code base in a second commit (but it's not a show-stopper if you don't feel like git'ing around).

Thanks for your review. I think it makes sense to separate all the vendoring stuff, the PR is now split in two commits.

**Comment by eshepelyuk** [comment]
@rg2011 since you've mentioned adjustment of code for `go vet` and `statickcheck` - I suggest to add those commands to CI pipeline as part of this PR.
Add to `justfile` and call them from `build.yaml`

**Comment by rg2011** [comment]
> @rg2011 since you've mentioned adjustment of code for `go vet` and `statickcheck` - I suggest to add those commands to CI pipeline as part of this PR. Add to `justfile` and call them from `build.yaml`

@eshepelyuk please review 526b43f. I included a new `test/go/test.sh` script based on the ones for helm and e2e. Latest run worked (https://github.com/open-policy-agent/kube-mgmt/actions/runs/1899924310).

**Comment by srenatus** [comment]
Thanks for going the extra mile. I'll merge this.

💭 The two separate commits have the disadvantage that there's a moment in the repo where it won't build if you checkout the first commit, code changes, and not the vendoring update; but I guess that's acceptable.

**Pull request merged**
