### PR TITLE
fix: simplify rbac creation

### PR DESCRIPTION
**Pull request by eshepelyuk**
Signed-off-by: Ievgenii Shepeliuk <eshepelyuk@gmail.com>

### CODE REVIEW

**Review by ashutosh-narkar — APPROVED** [review]
@eshepelyuk have you tested these changes ?

**Comment by eshepelyuk** [comment]
> @eshepelyuk have you tested these changes ?

Of course.

**Comment by CarloColumna** [comment]
Hey @eshepelyuk just wondering with this change how can you now set rbac rules to allow to allow permissions to replicate other k8s objects such as ingresses or deployments?

**Comment by eshepelyuk** [comment]
Hey @CarloColumna 
Is there any good reason to ask smth under the closed issue ?
The question is rhetorical, plz dont answer it.

1.if you have a general question, there is OPA slack
1. If you have specific question to me - I am there in OPA slack
1. If there is a bug / regression / improvement - plz open an issue 

Just pick up one of the options.

**Comment by CarloColumna** [comment]
I'll message you in Slack

**Comment by anderseknert** [comment]
@eshepelyuk I don't think there's anything wrong with asking questions on a closed issue or PR - that's often how people find their particular issue when searching for solutions. While moving the discussion to Slack might help whoever asked, it won't benefit anyone else looking for an answer to the same question. 

Definitely agree though that a new issue is the way to go if something is currently not working as expected.

**Comment by anderseknert** [comment]
Feel free to submit a PR for this @CarloColumna 👍

**Pull request merged**
